#!/usr/bin/env sh

proj_dir=$( cd $( dirname $0 ); pwd )
target_dir=$proj_dir/src/main/java

rm -rf $target_dir

mkdir -p $target_dir

cd $target_dir

# mkdir -p $target_dir/python
# omniidl -bpython -C$target_dir/python $proj_dir/*.idl

idlj -fall -td $target_dir $proj_dir/*.idl

