#!/usr/bin/env sh

set -e

this_dir=$( cd $( dirname $0 ); pwd )
target_dir=$this_dir

generated_dir=generated/

cd $this_dir

rm -rf $generated_dir

mkdir -p $generated_dir

cp ../tads-dsd-corba-idl/*.idl $generated_dir
cp run $generated_dir

cd $generated_dir

omniidl -bpython *.idl

