#!/usr/bin/env sh

this_dir=$( cd $( dirname $0 ); pwd )
target_dir=$this_dir/src/main/java

rm -rf $target_dir

mkdir -p $target_dir

cd $target_dir

idlj -fall -td $target_dir $this_dir/../tads-dsd-corba-idl/*.idl

