swagger: '2.0'
info:
  license:
    name: MIT
tags:
  - name: Calculadora
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /calculadora/somar:
    get:
      tags:
        - Calculadora
      operationId: somar
      parameters:
        - name: parcela1
          in: query
          required: true
          type: "number"
          format: "double"
        - name: parcela2
          in: query
          required: true
          type: "number"
          format: "double"
      responses:
        "200":
          schema:
            $ref: '#/definitions/Resultado'
definitions:
  Resultado:
    properties:
      valor:
        type: "number"
        format: "double"
